title: "Ozan Usta"
email: ozanusta2001@gmail.com
description: >-
  Master of Arts student in Interdisciplinary Studies of the Middle East (ISME)
  at Freie Universität Berlin. Interested in Turkish historiography, nation-building,
  and Middle Eastern studies.

baseurl: "" # leave blank for GitHub Pages
url: "https://ozanu22.github.io"

author:
  name: "Ozan Usta"
  email: ozanusta2001@gmail.com

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

